### PR TITLE
run with nvidia gpus

### PR DESCRIPTION
**Pull request by stingshen**
Fix running on machine with NVIDIA gpus.

[nvidia-container-runtime](https://nvidia.github.io/nvidia-container-runtime/) is required.

The idea is actually from:

https://github.com/huan/docker-wechat/issues/50#issuecomment-797792368

### CODE REVIEW

**Comment by huan** [comment]
Please make sure the following requirements have been met for your PR before we can continue reviewing it:

1. You have signed the CLA by clicking the `[CLA | not signed yet]` button from the comments.
2. The PR has passed all the CI tests and turns _green_. (you can execute all tests locally by running `npm test`)

**Review by huan — CHANGES_REQUESTED** [review]
Could you please bump the minor version for the project, so that we will have a new version for this PR?

For example, we can bump the version from `v0.14.4` to `v0.15.0` in the below file, and the GitHub Action will CI/CD a new version from the file:

- https://github.com/huan/docker-wechat/blob/main/VERSION

**Comment by stingshen** [comment]
> Could you please bump the minor version for the project, so that we will have a new version for this PR?
> 
> For example, we can bump the version from `v0.14.4` to `v0.15.0` in the below file, and the GitHub Action will CI/CD a new version from the file:
> 
> * https://github.com/huan/docker-wechat/blob/main/VERSION

done

**Review by huan — CHANGES_REQUESTED** [review]
LGTM

Thank you very much for the contribution!

**Review by huan — APPROVED** [review]

**Pull request merged**
